workflows:
  ios-app:
    name: thaimon2025
    environment:
      xcode: latest
      cocoapods: default
      vars:
        PROJ_DIR: "game_project/MyLuaGame/frameworks/pokemon_proj_tc_qd/proj.ios_mac"
        COCOS_CONSOLE: "game_project/MyLuaGame/frameworks/cocos2d-x/tools/cocos2d-console/bin/cocos.py"

    scripts:
      - name: Set up Xcode and Python
        script: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools six
          echo "✅ Xcode and Python setup complete!"

      - name: Install dependencies
        script: |
          brew update
          brew install wget
          brew install rar
          brew install pyenv  # ใช้ pyenv เพื่อติดตั้ง Python 2.7
          
          # ติดตั้ง Python 2.7 ผ่าน pyenv
          pyenv install 2.7.18 || true
          pyenv global 2.7.18
          
          # สร้างคำสั่ง python2 ให้ใช้งานได้
          ln -sf "$(pyenv root)/versions/2.7.18/bin/python" /usr/local/bin/python2 || true
          ln -sf "$(pyenv root)/versions/2.7.18/bin/python" /usr/bin/python2 || true

          # ตรวจสอบว่า Python 2 ติดตั้งสำเร็จหรือไม่
          if ! python2 --version &> /dev/null; then
              echo "❌ Python 2.7 ไม่สามารถใช้งานได้"
              exit 1
          fi

          echo "✅ Python 2.7 ติดตั้งสำเร็จ"

          pip3 install gdown
          pip3 install lz4 numpy xlrd cython six

      - name: Check Python 2 Availability
        script: |
          if ! python2 --version &> /dev/null
          then
              echo "❌ Python2 ไม่พร้อมใช้งาน หยุดการทำงาน"
              exit 1
          else
              echo "✅ Python2 พร้อมใช้งาน"
              python2 --version
          fi

      - name: Download Project from Google Drive
        script: |
          gdown --id 1gQL8yD39YqkAos4wQu7b1abElcBe16CS -O MyLuaGame.rar
          mkdir -p game_project
          cd game_project
          unrar x -o+ ../MyLuaGame.rar

      - name: Download and Extract Tools
        script: |
          # ดาวน์โหลด tools.rar ไปที่ root directory
          gdown --id 1JikTcspkqxMVeO1WtfPc5dJ4Ca6VCFAm -O tools.rar
          
          # แตกไฟล์ tools.rar เหมือนกับ MyLuaGame.rar
          mkdir -p tools
          cd tools
          unrar x -o+ ../tools.rar


      - name: Build iOS IPA
        script: |
          cd $PROJ_DIR
          python2 ../../cocos2d-x/tools/cocos2d-console/bin/cocos.py deploy -p ios -m release -j8 --agreement n
          
    artifacts:
      - build/ios/*.ipa
