workflows:
  ios-app:
    name: thaimon2025
    environment:
      xcode: latest
      cocoapods: default
      vars:
        PROJ_DIR: "game_project/MyLuaGame/frameworks/pokemon_proj_tc_qd/proj.ios_mac"
        COCOS_CONSOLE: "game_project/MyLuaGame/frameworks/cocos2d-x/tools/cocos2d-console/bin/cocos.py"

    scripts:
      - name: Set up Xcode and Python
        script: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools six
          echo "✅ Xcode and Python setup complete!"

      - name: Install dependencies
        script: |
          brew update
          brew install wget
          brew install rar
          brew install python@2  # ติดตั้ง Python 2
          
          # ตรวจสอบว่า Python 2 ติดตั้งสำเร็จหรือไม่
          if [ ! -f "/usr/local/bin/python2.7" ]; then
              echo "❌ Python2.7 ไม่ถูกติดตั้ง"
              exit 1
          fi
          
          # สร้าง symlink ให้ python2 ใช้งานได้
          ln -sf /usr/local/bin/python2.7 /usr/local/bin/python2
          echo "✅ Python2 ติดตั้งเรียบร้อย"

          pip3 install gdown
          pip3 install lz4 numpy xlrd cython six

      - name: Check Python 2 Availability
        script: |
          if ! command -v python2 &> /dev/null
          then
              echo "❌ Python2 ไม่พร้อมใช้งาน หยุดการทำงาน"
              exit 1
          else
              echo "✅ Python2 พร้อมใช้งาน"
              python2 --version
          fi

      - name: Download Project from Google Drive
        script: |
          gdown --id 1GeF9nGtrvSkZEXYZ0W6lxY0oujzzEi7p -O MyLuaGame.rar
          mkdir -p game_project
          cd game_project
          unrar x -o+ ../MyLuaGame.rar

      - name: Build iOS IPA
        script: |
          cd $PROJ_DIR
          python2 ../../cocos2d-x/tools/cocos2d-console/bin/cocos.py deploy -p ios -m release -j8
          
    artifacts:
      - build/ios/*.ipa
