workflows:
  ios-app:
    name: thaimon2025
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          brew update
          brew install wget
          brew install rar
          pip install gdown
          
      - name: Download Project from Google Drive
        script: |
          gdown --id 1z1LGmzuQoxk5cHsyf6T4aRBnzEFfUHQf -O MyLuaGame.rar
          mkdir -p game_project
          cd game_project
          unrar x -o+ ../MyLuaGame.rar
          
      - name: Build iOS IPA
        script: |
          cd game_project/MyLuaGame/frameworks/pokemon_proj_tc_qd/proj.ios_mac
          python ../../../bin/cocos.py deploy -p ios -m release
          
    artifacts:
      - build/ios/*.ipa
