workflows:
  ios-app:
    name: thaimon2025
    environment:
      xcode: latest
      cocoapods: default
      vars:
        PROJ_DIR: "game_project/MyLuaGame/frameworks/pokemon_proj_tc_qd/proj.ios_mac"
        COCOS_CONSOLE: "game_project/MyLuaGame/frameworks/cocos2d-x/tools/cocos2d-console/bin/cocos.py"

    scripts:
      - name: Set up Xcode and Python
        script: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools six
          echo "Xcode and Python setup complete!"

      - name: Install dependencies
        script: |
          brew update
          brew install wget
          brew install rar
          pip3 install --upgrade gdown
          pip3 install lz4 numpy xlrd cython six

      - name: Install Google Drive CLI
        script: |
          echo "✅ ดาวน์โหลดและติดตั้ง gdrive CLI"
          curl -L -o gdrive.tar.gz "https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive-linux-x64.tar.gz"
          tar -xzf gdrive.tar.gz
          chmod +x gdrive
          sudo mv gdrive /usr/local/bin/

      - name: Download Project from Google Drive
        script: |
          echo "✅ ดาวน์โหลดไฟล์จาก Google Drive"
          gdrive download --id 1z1LGmzuQoxk5cHsyf6T4aRBnzEFfUHQf --force
          
          echo "✅ ตรวจสอบไฟล์ที่โหลดมา:"
          ls -lah MyLuaGame.rar
          file MyLuaGame.rar

          mkdir -p game_project
          cd game_project
          unrar x -o+ ../MyLuaGame.rar

      - name: Build iOS IPA
        script: |
          cd $PROJ_DIR
          python3 ../../cocos2d-x/tools/cocos2d-console/bin/cocos.py deploy -p ios -m release -j8
          
    artifacts:
      - build/ios/*.ipa
